version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: secureauth-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: .
    container_name: secureauth-api
    restart: unless-stopped
    ports:
      - "5000:8080"   # host:container
    environment:
      ASPNETCORE_URLS: "http://+:8080"
      ASPNETCORE_ENVIRONMENT: "Development"  # roda migrations automaticamente
    depends_on:
      - postgres
    env_file:
      - .env
    volumes:
      - data-protection:/root/.aspnet/DataProtection-Keys
    command: ["dotnet", "SecureAuth.API.dll"]

  pgadmin:
    image: dpage/pgadmin4:9.8
    container_name: secureauth-pgadmin
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'

volumes:
  pgdata:
  data-protection: